services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-master.sh && tail -f /dev/null"]
    volumes:
      - ./workspace:/opt/spark/workspace
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark_net

  spark-worker-1:
    image: spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-worker.sh $SPARK_MASTER && tail -f /dev/null"]
    volumes:
      - ./workspace:/opt/spark/workspace
    depends_on:
      - spark-master
    networks:
      - spark_net

  spark-worker-2:
    image: spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-worker.sh $SPARK_MASTER && tail -f /dev/null"]
    volumes:
      - ./workspace:/opt/spark/workspace
    depends_on:
      - spark-master
    networks:
      - spark_net

networks:
  spark_net:
    # (Only if net external)
    # external: true
    # name: postgres_streaming_default