services:
  spark-master:
    image: bitnamilegacy/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./workspace:/opt/spark/workspace
    ports:
      - "8082:8080"   # Dashboard Spark
      - "7077:7077"   # Port pour les workers
    networks:
      - spark_net

  spark-worker-1:
    image: bitnamilegacy/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./workspace:/opt/spark/workspace
    depends_on:
      - spark-master
    networks:
      - spark_net

  spark-worker-2:
    image: bitnamilegacy/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./workspace:/opt/spark/workspace
    depends_on:
      - spark-master
    networks:
      - spark_net

networks:
  spark_net:
    # (Only if net external)
    # external: true
    # name: postgres_streaming_default